.\Man page for Gusto
.TH Gusto 1 2023-01-30
.SH NAME
Gusto \- A program to convert video or sections of a video to images (GTK+, GStreamer)
.SH SYNOPSIS
.B Gusto
.SH DESCRIPTION
\fBGusto\fR is intended to convert video to images. 
It is possible to convert a complete video or a time based section of a video 
or you may also convert selected frames.

Numerous video and image formats are provided for.
.SH OPTIONS
Gusto has no options
.SH EXIT STATUS
On success Gusto will exit(0); on error it will exit(-1). 
.SH FILES
.TP
All image files output are placed in the directory specified and images are named with the selected prefix. Defaults are preset. 
.SH BUGS
Gusto is currently Beta software and is reasonably stable. However bugs may be 
encountered from time to time. Should this happen, please provide details to the 
author. 
.SH AUTHOR
Gusto and this manual page were written by Anthony Buckley <tony.buckley0000@gmail.com>
